package org.apache.spark.mllib.classification

import org.scalatest.FunSuite
import org.apache.spark.streaming.dstream.DStream
import org.apache.spark.util.random.XORShiftRandom

/** This is to test correctness and functionality of streaming
  * Naive Bayes algorithm. Firstly, we should guarantee that the
  * same result as batch training implementation is generated by our implementation.
  * Secondly, we should generate time-changing model to test its adaptability to
  * ever-changing data model in practice.
  */

class StreamingNaiveBayesSuite extends FunSuite {


}

